# Brain Rot Project - Data Exploration

## 0. Import Libraries

In [ ]:
import pandas as pd
import numpy as np

# This makes pandas show all columns when we print a table
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

print("Libraries imported successfully")

Libraries imported successfully

## 1. Load the Data

In [5]:
# Load all 5 csv files into pandas dataframes
path = r"F:\Data Analysis\DEPI\Final Final Project\Depi-Data-Analysis-Project(github project structure)\raw_data"

df_fact = pd.read_csv(f"{path}/Fact_User_Activity.csv")
df_users = pd.read_csv(f"{path}/Dim_Users.csv")
df_habits = pd.read_csv(f"{path}/Dim_Habits.csv")
df_mentalstate = pd.read_csv(f"{path}/Dim_MentalState.csv")
df_date = pd.read_csv(f"{path}/Dim_Date.csv")

print("All files loaded successfully!")

All files loaded successfully!

## 2. Fact_User_Activity Table

In [7]:
print("Shape:", df_fact.shape)

Shape: (5000, 14)

In [8]:
df_fact.columns.tolist()

['ActivityID',
 'UserKey',
 'DateKey',
 'StateKey',
 'HabitKey',
 'Study_Hours',
 'Coffee_Consumed_Per_Day',
 'Smoking_Breaks_Count',
 'Total_Reels_Watched',
 'Short_Content_Percentage',
 'Peak_Hour',
 'Focus_Sessions_Count',
 'Brainrot_Exposure_Score',
 'Wellbeing_Score']

In [9]:
df_fact.head()

,ActivityID,UserKey,DateKey,StateKey,HabitKey,Study_Hours,Coffee_Consumed_Per_Day,Smoking_Breaks_Count,Total_Reels_Watched,Short_Content_Percentage,Peak_Hour,Focus_Sessions_Count,Brainrot_Exposure_Score,Wellbeing_Score
0,1,90,20261008,4,2,5.4,1,9,198,0.75,16,3,94.82,20.18
1,2,62,20260108,1,2,7.6,3,0,2,0.41,22,9,0.00,100.00
2,3,45,20260320,2,2,1.2,2,0,125,0.77,23,2,57.00,53.00
3,4,76,20261121,1,3,3.5,2,11,18,0.41,0,6,10.03,100.00
4,5,66,20260414,1,1,5.5,0,0,27,0.46,16,5,3.56,100.00

In [10]:
df_fact.tail()

,ActivityID,UserKey,DateKey,StateKey,HabitKey,Study_Hours,Coffee_Consumed_Per_Day,Smoking_Breaks_Count,Total_Reels_Watched,Short_Content_Percentage,Peak_Hour,Focus_Sessions_Count,Brainrot_Exposure_Score,Wellbeing_Score
4995,4996,79,20260417,1,1,2.7,0,0,89,0.45,23,4,23.45,96.55
4996,4997,37,20260112,1,2,7.1,5,0,21,0.48,9,7,0.00,100.00
4997,4998,48,20260908,1,1,3.7,0,0,62,0.44,17,5,11.96,100.00
4998,4999,14,20260630,1,2,6.9,2,0,38,0.43,15,8,0.00,100.00
4999,5000,6,20261013,1,2,4.8,1,0,28,0.47,19,8,0.00,100.00

In [11]:
df_fact.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ActivityID                5000 non-null   int64
 1   UserKey                   5000 non-null   int64
 2   DateKey                   5000 non-null   int64
 3   StateKey                  5000 non-null   int64
 4   HabitKey                  5000 non-null   int64
 5   Study_Hours               5000 non-null   float64
 6   Coffee_Consumed_Per_Day   5000 non-null   int64
 7   Smoking_Breaks_Count      5000 non-null   int64
 8   Total_Reels_Watched       5000 non-null   int64
 9   Short_Content_Percentage  5000 non-null   float64
 10  Peak_Hour                 5000 non-null   int64
 11  Focus_Sessions_Count      5000 non-null   int64
 12  Brainrot_Exposure_Score   5000 non-null   float64
 13  Wellbeing_Score           5000 non-null   float64
dtypes: float64(4), int64(10)
memory usage: 547.0 KB

In [12]:
df_fact.describe()

,ActivityID,UserKey,DateKey,StateKey,HabitKey,Study_Hours,Coffee_Consumed_Per_Day,Smoking_Breaks_Count,Total_Reels_Watched,Short_Content_Percentage,Peak_Hour,Focus_Sessions_Count,Brainrot_Exposure_Score,Wellbeing_Score
count,5000.000000,5000.000000,5.000000e+03,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,50.949600,2.026067e+07,1.879600,1.87080,3.957800,1.653800,1.304400,91.00680,0.567646,15.923200,3.700600,37.696576,70.134932
std,1443.520003,28.926459,3.437548e+02,1.202411,0.56229,2.215654,2.003684,3.154256,70.24807,0.170765,6.724935,2.502281,36.173731,37.562957
min,1.000000,1.000000,2.026010e+07,1.000000,1.00000,0.000000,0.000000,0.000000,2.00000,0.400000,0.000000,0.000000,0.000000,0.000000
25%,1250.750000,26.000000,2.026040e+07,1.000000,2.00000,2.300000,0.000000,0.000000,33.00000,0.430000,12.000000,2.000000,5.160000,30.815000
50%,2500.500000,51.000000,2.026070e+07,1.000000,2.00000,3.700000,1.000000,0.000000,70.00000,0.470000,18.000000,4.000000,22.900000,96.080000
75%,3750.250000,76.250000,2.026100e+07,3.000000,2.00000,5.400000,2.000000,0.000000,160.00000,0.770000,21.000000,6.000000,76.792500,100.000000
max,5000.000000,100.000000,2.026123e+07,4.000000,3.00000,10.900000,9.000000,14.000000,269.00000,0.830000,23.000000,11.000000,100.000000,100.000000

In [13]:
df_fact.isnull().sum()

ActivityID                  0
UserKey                     0
DateKey                     0
StateKey                    0
HabitKey                    0
Study_Hours                 0
Coffee_Consumed_Per_Day     0
Smoking_Breaks_Count        0
Total_Reels_Watched         0
Short_Content_Percentage    0
Peak_Hour                   0
Focus_Sessions_Count        0
Brainrot_Exposure_Score     0
Wellbeing_Score             0
dtype: int64

In [14]:
print("Duplicated rows:", df_fact.duplicated().sum())

Duplicated rows: 0

## 3. Dim_Users Table

In [15]:
print("Shape:", df_users.shape)

Shape: (99, 8)

In [17]:
print(df_users.columns.tolist())

['UserKey', 'Username', 'Age', 'Age_Group', 'Region', 'Device_Type', 'Is_Smoker', 'Base_Focus_Level']

In [18]:
df_users.head()

   UserKey Username  Age Age_Group Region Device_Type  Is_Smoker  Base_Focus_Level
0        1   User_1   18      Teen   Suez  Smartphone          1                81
1        2   User_2   11     Child   Suez  Smartphone          0                84
2        3   User_3   24     Young  Asyut      Tablet          0                62
3        4   User_4   16      Teen   Suez  Smartphone          0                73
4        5   User_5   15      Teen  Asyut  Smartphone          1                86

In [20]:
df_users.tail()

    UserKey Username  Age Age_Group Region Device_Type  Is_Smoker  Base_Focus_Level
94       95  User_95   17      Teen  Aswan      Tablet          0                67
95       96  User_96   11     Child   Giza  Smartphone          0                84
96       97  User_97   16      Teen  Cairo      Tablet          0                88
97       98  User_98   15      Teen  Minya  Smartphone          1                79
98       99  User_99   22     Young  Cairo  Smartphone          0                67

In [21]:
df_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   UserKey           99 non-null     int64
 1   Username          99 non-null     object
 2   Age               99 non-null     int64
 3   Age_Group         99 non-null     object
 4   Region            99 non-null     object
 5   Device_Type       99 non-null     object
 6   Is_Smoker         99 non-null     int64
 7   Base_Focus_Level  99 non-null     int64
dtypes: int64(4), object(4)
memory usage: 6.3+ KB

In [22]:
df_users.describe()

         UserKey        Age  Is_Smoker  Base_Focus_Level
count  99.000000  99.000000  99.000000         99.000000
mean   50.000000  15.555556   0.202020         77.393939
std    28.722813   4.636198   0.403551         11.408749
min     1.000000   8.000000   0.000000         60.000000
25%    25.500000  12.000000   0.000000         67.000000
50%    50.000000  15.000000   0.000000         76.000000
75%    74.500000  19.000000   0.000000         88.000000
max    99.000000  25.000000   1.000000         95.000000

In [23]:
df_users.isnull().sum()

UserKey             0
Username            0
Age                 0
Age_Group           0
Region              0
Device_Type         0
Is_Smoker           0
Base_Focus_Level    0
dtype: int64

In [24]:
print("Duplicated rows:", df_users.duplicated().sum())

Duplicated rows: 0

## 4. Dim_Habits Table

In [25]:
print("Shape:", df_habits.shape)
df_habits

Shape: (3, 3)

   HabitKey Coffee_Level Smoking_Status
0         1          NaN     Non-Smoker
1         2     Moderate     Occasional
2         3       Addict   Heavy-Smoker

In [26]:
df_habits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   HabitKey        3 non-null      int64
 1   Coffee_Level    2 non-null      object
 2   Smoking_Status  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [27]:
df_habits.isnull().sum()

HabitKey          0
Coffee_Level      1
Smoking_Status    0
dtype: int64

In [28]:
print("Duplicated rows:", df_habits.duplicated().sum())

Duplicated rows: 0

## 5. Dim_MentalState Table

In [29]:
print("Shape:", df_mentalstate.shape)
df_mentalstate

Shape: (4, 4)

   StateKey Attention_Span_Level Brainrot_Stage Aura_Color_Code
0         1                 High        Healthy           Green
1         2               Medium         Casual          Yellow
2         3               Cooked       Advanced             Red
3         4                Fried       Critical             Red

In [30]:
df_mentalstate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StateKey              4 non-null      int64
 1   Attention_Span_Level  4 non-null      object
 2   Brainrot_Stage        4 non-null      object
 3   Aura_Color_Code       4 non-null      object
dtypes: int64(1), object(3)
memory usage: 260.0+ bytes

In [31]:
df_mentalstate.isnull().sum()

StateKey                0
Attention_Span_Level    0
Brainrot_Stage          0
Aura_Color_Code         0
dtype: int64

In [32]:
print("Duplicated rows:", df_mentalstate.duplicated().sum())

Duplicated rows: 0

## 6. Dim_Date Table

In [33]:
print("Shape:", df_date.shape)
df_date.head()

Shape: (365, 5)

    DateKey  FullDate  Is_Late_Night  Is_Exam_Season  Is_Weekend
0  20260101  1/1/2026              0               1           0
1  20260102  1/2/2026              0               1           1
2  20260103  1/3/2026              0               1           1
3  20260104  1/4/2026              1               1           0
4  20260105  1/5/2026              0               1           0

In [34]:
df_date.tail()

      DateKey    FullDate  Is_Late_Night  Is_Exam_Season  Is_Weekend
360  20261227  12/27/2026              0               0           0
361  20261228  12/28/2026              1               0           0
362  20261229  12/29/2026              0               0           0
363  20261230  12/30/2026              1               0           0
364  20261231  12/31/2026              1               0           0

In [35]:
df_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   DateKey         365 non-null    int64
 1   FullDate        365 non-null    object
 2   Is_Late_Night   365 non-null    int64
 3   Is_Exam_Season  365 non-null    int64
 4   Is_Weekend      365 non-null    int64
dtypes: int64(4), object(1)
memory usage: 14.4+ KB

In [36]:
df_date.isnull().sum()

DateKey           0
FullDate          0
Is_Late_Night     0
Is_Exam_Season    0
Is_Weekend        0
dtype: int64

In [37]:
print("Duplicated rows:", df_date.duplicated().sum())

Duplicated rows: 0

## 7. Checking Data Types

In [38]:
print("Fact_User_Activity dtypes:")
print(df_fact.dtypes)
print()
print("Dim_Users dtypes:")
print(df_users.dtypes)
print()
print("Dim_Habits dtypes:")
print(df_habits.dtypes)
print()
print("Dim_MentalState dtypes:")
print(df_mentalstate.dtypes)
print()
print("Dim_Date dtypes:")
print(df_date.dtypes)

Fact_User_Activity dtypes:
ActivityID                    int64
UserKey                       int64
DateKey                       int64
StateKey                      int64
HabitKey                      int64
Study_Hours                 float64
Coffee_Consumed_Per_Day       int64
Smoking_Breaks_Count          int64
Total_Reels_Watched           int64
Short_Content_Percentage    float64
Peak_Hour                     int64
Focus_Sessions_Count          int64
Brainrot_Exposure_Score     float64
Wellbeing_Score             float64
dtype: object

Dim_Users dtypes:
UserKey              int64
Username            object
Age                  int64
Age_Group           object
Region              object
Device_Type         object
Is_Smoker            int64
Base_Focus_Level     int64
dtype: object

Dim_Habits dtypes:
HabitKey           int64
Coffee_Level      object
Smoking_Status    object
dtype: object

Dim_MentalState dtypes:
StateKey                 int64
Attention_Span_Level    object
Brainrot_Stage          object
Aura_Color_Code         object
dtype: object

Dim_Date dtypes:
DateKey            int64
FullDate          object
Is_Late_Night      int64
Is_Exam_Season     int64
Is_Weekend         int64
dtype: object

## 8. Unique Values in Important Categorical Columns

In [41]:
print("Age_Group values:", df_users['Age_Group'].unique())
print()
print("Region values:", df_users['Region'].unique())
print()
print("Device_Type values:", df_users['Device_Type'].unique())
print()
print("Coffee_Level values:", df_habits['Coffee_Level'].unique())
print()
print("Smoking_Status values:", df_habits['Smoking_Status'].unique())
print()
print("Attention_Span_Level values:", df_mentalstate['Attention_Span_Level'].unique())
print()
print("Brainrot_Stage values:", df_mentalstate['Brainrot_Stage'].unique())
print()
print("Aura_Color_Code values:", df_mentalstate['Aura_Color_Code'].unique())

Age_Group values: ['Teen' 'Child' 'Young']

Region values: ['Suez' 'Asyut' 'Alexandria' 'Cairo' 'Tanta' 'Aswan' 'Port Said' 'Giza'
 'Luxor' 'Mansoura' 'Minya']

Device_Type values: ['Smartphone' 'Tablet' 'PC']

Coffee_Level values: [nan 'Moderate' 'Addict']

Smoking_Status values: ['Non-Smoker' 'Occasional' 'Heavy-Smoker']

Attention_Span_Level values: ['High' 'Medium' 'Cooked' 'Fried']

Brainrot_Stage values: ['Healthy' 'Casual' 'Advanced' 'Critical']

Aura_Color_Code values: ['Green' 'Yellow' 'Red']

## 9. Simple Frequency Tables

In [43]:
print("How many users per Age_Group:")
print(df_users['Age_Group'].value_counts())
print()
print("How many users per Region:")
print(df_users['Region'].value_counts())
print()
print("How many users per Device_Type:")
print(df_users['Device_Type'].value_counts())
print()
print("How many activity records per Brainrot Stage (using StateKey for now):")
print(df_fact['StateKey'].value_counts())

How many users per Age_Group:
Age_Group
Teen     46
Child    27
Young    26
Name: count, dtype: int64

How many users per Region:
Region
Suez          16
Luxor         11
Cairo         10
Aswan         10
Asyut          9
Mansoura       9
Tanta          9
Giza           9
Port Said      6
Minya          6
Alexandria     4
Name: count, dtype: int64

How many users per Device_Type:
Device_Type
Smartphone    72
Tablet        18
PC             9
Name: count, dtype: int64

How many activity records per Brainrot Stage (using StateKey for now):
StateKey
1    3044
4     907
3     628
2     421
Name: count, dtype: int64